#trigger on push to master
on:
  push:
    branches:
      - main

#build docker image and push to docker hub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: philips-software/docker-ci-scripts@v4.5.0
        with:
          dockerfile: "Dockerfile"
          #image name from repository
          image-name: "tensorflow-cuda-conda"
          tags: "latest base"
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_URL: ghcr.io/jrgrant-uliv
          GITHUB_ORGANIZATION: jrgrant-uliv



