#trigger on push to master
on:
  push:
    branches:
      - main

#build docker image and push to docker hub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.12
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: tensorflow-cuda-conda # Provide Docker image name
          pull-image: true # Raise the flag to try to pull image
