#trigger on push to master
on:
  push:
    branches:
      - main

#build docker image and push to docker hub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish head Docker image
        uses: TCPShield/gp-docker-action@1.1.13
        with:
            github-username: ${{ github.actor }} # Provide GitHub username
            github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
            image-name: ${{ github.repository }} # Provide Docker image name
            image-tag: latest base
            # image-name: my-cool-service # Provide Docker image name
            # pull-image: true # Raise the flag to try to pull image