#trigger on push to master
on:
  push:
    branches:
      - main

#build docker image and push to github packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest
      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push the Docker image
        run: docker push docker.pkg.github.com/${{ github.repository }}:latest



