name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #   - name: Set up Docker
    #     uses: docker/setup-action@v2

      - name: Extract tag from commit message
        run: |
          export TAG=$(grep -oP '(?<=#TAG=)[^\s]*' <<< "$(git log -1 --pretty=%B)")
        shell: bash

      - name: Build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Create GitHub release
        if: env.TAG
        run: |
          git tag $TAG
          git push origin $TAG
          body="Release $TAG"
          hub release create -m $TAG -m "$body" $TAG
